apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Clients
  namespace: Clients
spec:
  replicas: 1
  template:
  metadata:
    labels:
    k8s-app: Clients
  spec:
    containers:
    - name: Clients
      image: Clients:0.1
      imagePullPolicy: "IfNotPresent"
      ports:
      - containerPort: 5000
      volumeMounts:
        - mountPath: /app-data
          name: Clients
     volumes: 
         - name: <name of application>
           persistentVolumeClaim:
             claimName: appclaim1