apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-disk1
  namespace: Clients
spec:
  capacity:
  storage: 50Gi
  accessModes:
  - ReadWriteMany
  cephfs:
  monitors:
    - "172.0.0.1:5000"
  user: admin
  secretRef:
    name: ceph-secret
  readOnly: false